site_name: MkDocs - Open in new tab plugin
site_url: https://jakubandrysek.github.io/mkdocs-open-in-new-tab/
site_author: Jakub Andrýsek
site_description: >-
  MkDocs plugin to open outgoing links and PDFs in new tab.

# Repository
repo_name: JakubAndrysek/mkdocs-open-in-new-tab
repo_url: https://newtab.kubaandrysek.cz/

# Copyright
copyright: Copyright © 2023 Jakub Andrýsek

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top

  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: slate
      primary: red
      accent: red

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JakubAndrysek
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/KubaAndrysek
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jakub-andrysek/
#    analytics:
#        provider: google
#        property: G-XXXXXXXXXX

use_directory_urls: True

plugins:
  - search
  - open-in-new-tab


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences



nav:
  - Home: 'README.md'
